const el=s=>document.getElementById(s);
const productsEl=el('products'),search=el('search'),volume=el('volume'),neck=el('neck'),category=el('category'),minVolume=el('minVolume'),maxVolume=el('maxVolume'),minOut=el('minOut'),maxOut=el('maxOut'),counter=el('counter'),mobileCount=el('mobileCount');
const catNames={strong:'Крепкий алкоголь',soft:'Безалкогольные напитки',still:'Тихие вина',sparkling:'Игристые вина',food:'Пищевые продукты / масла'};
function decode(s){return String(s).replace(/#U([0-9A-Fa-f]{4})/g,(_,h)=>String.fromCharCode(parseInt(h,16)));}
function safe(s){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
function getName(p){return decode(p.name)}
function getNeck(p){const n=getName(p);const m=n.match(/^(КПМ|КПН|КПР|Вн|В|П|ТО|TO)[-_]?([0-9]{1,3})/i);return m?`${m[1]}-${m[2]}`:'Другие';}
const necks=[...new Set(PRODUCTS.map(getNeck))].sort((a,b)=>a.localeCompare(b,'ru',{numeric:true}));necks.forEach(n=>{const o=document.createElement('option');o.value=n;o.textContent=n;neck.appendChild(o)});
const vols=[...new Set(PRODUCTS.map(p=>parseInt(p.volume,10)).filter(Number.isFinite))].sort((a,b)=>a-b);vols.forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v+' мл';volume.appendChild(o)});if(vols.length){minVolume.min=Math.min(...vols);minVolume.max=Math.max(...vols);maxVolume.min=Math.min(...vols);maxVolume.max=Math.max(...vols);minVolume.value=Math.min(...vols);maxVolume.value=Math.max(...vols);}
el('totalModels').textContent=PRODUCTS.length;
function render(){let a=PRODUCTS.slice();const q=search.value.toLowerCase().trim(),v=volume.value,n=neck.value,c=category.value;let lo=parseInt(minVolume.value,10),hi=parseInt(maxVolume.value,10);if(lo>hi)[lo,hi]=[hi,lo];minOut.textContent=lo;maxOut.textContent=hi;a=a.filter(p=>{const name=getName(p).toLowerCase(),pv=parseInt(p.volume,10);return(!q||name.includes(q))&&(!v||String(p.volume)===v)&&(!n||getNeck(p)===n)&&(!c||p.category===c)&&(!Number.isFinite(pv)||pv>=lo&&pv<=hi)});counter.textContent=`Найдено: ${a.length}`;mobileCount.textContent=`${a.length} поз.`;productsEl.innerHTML=a.map(p=>{const i=PRODUCTS.indexOf(p),name=safe(getName(p)),img=imgPath(p.images?.[0]||'');return `<article class="card"><div class="card-photo" data-i="${i}"><img src="${img}" alt="Стеклянная бутылка ${name}" loading="lazy" onerror="this.style.display='none'"></div><div class="card-body"><h3>${name}</h3><div class="meta">${p.volume||'—'} мл · ${catNames[p.category]||'Стеклянная тара'} · ${getNeck(p)}</div><div class="actions"><button class="primary" data-detail="${i}">Подробнее</button><button data-order="${i}">Запросить цену</button></div></div></article>`}).join('')||'<div class="empty">По заданным параметрам модели не найдены.</div>';}
const ru={'А':'A','Б':'B','В':'V','Г':'G','Д':'D','Е':'E','Ё':'E','Ж':'Zh','З':'Z','И':'I','Й':'Y','К':'K','Л':'L','М':'M','Н':'N','О':'O','П':'P','Р':'R','С':'S','Т':'T','У':'U','Ф':'F','Х':'Kh','Ц':'Ts','Ч':'Ch','Ш':'Sh','Щ':'Sch','Ъ':'','Ы':'Y','Ь':'','Э':'E','Ю':'Yu','Я':'Ya','а':'a','б':'b','в':'v','г':'g','д':'d','е':'e','ё':'e','ж':'zh','з':'z','и':'i','й':'y','к':'k','л':'l','м':'m','н':'n','о':'o','п':'p','р':'r','с':'s','т':'t','у':'u','ф':'f','х':'kh','ц':'ts','ч':'ch','ш':'sh','щ':'sch','ъ':'','ы':'y','ь':'','э':'e','ю':'yu','я':'ya'};
function imgPath(name){return 'assets/images/'+decode(name).split('').map(c=>ru[c]??c).join('').replace(/[^A-Za-z0-9._ -]/g,'_').replace(/ /g,'_').replace(/_+/g,'_');}
productsEl.addEventListener('click',e=>{const det=e.target.closest('[data-detail]'),ord=e.target.closest('[data-order]');if(det)openDetail(+det.dataset.detail);if(ord)orderProduct(+ord.dataset.order);});
[search,volume,neck,category,minVolume,maxVolume].forEach(x=>x.addEventListener('input',render));el('resetFilters').onclick=()=>{search.value='';volume.value='';neck.value='';category.value='';minVolume.value=minVolume.min;maxVolume.value=maxVolume.max;render()};
function openDetail(i){const p=PRODUCTS[i],name=getName(p),img=imgPath(p.images?.[0]||'');el('detailContent').innerHTML=`<div class="detail-content"><div class="detail-photo"><img src="${img}" alt="Стеклянная бутылка ${safe(name)}"></div><div class="detail-info"><div class="eyebrow">КАТАЛОГ</div><h2>${safe(name)}</h2><table class="detail-table"><tr><td>Объём</td><td>${p.volume||'Уточняется'} мл</td></tr><tr><td>Серия венчика</td><td>${safe(getNeck(p))}</td></tr><tr><td>Категория</td><td>${safe(catNames[p.category]||'Стеклянная тара')}</td></tr><tr><td>Фотографий</td><td>${p.images?.length||1}</td></tr></table><p>Точные технические параметры и условия поставки уточняются по запросу для конкретной партии.</p><button class="btn btn-primary" data-order-modal="${i}">Запросить цену</button></div></div>`;el('detailModal').classList.add('open');el('detailContent').querySelector('[data-order-modal]').onclick=()=>orderProduct(i);}
function orderProduct(i){el('productField').value=getName(PRODUCTS[i]);el('detailModal').classList.remove('open');document.getElementById('contacts').scrollIntoView({behavior:'smooth'});}
el('closeDetail').onclick=()=>el('detailModal').classList.remove('open');
el('openFilters').onclick=()=>{el('filters').classList.add('open');el('backdrop').classList.add('open')};el('closeFilters').onclick=closeFilters;el('backdrop').onclick=closeFilters;function closeFilters(){el('filters').classList.remove('open');el('backdrop').classList.remove('open')};
el('menuBtn').onclick=()=>{const n=el('mobileNav');const open=n.classList.toggle('open');el('menuBtn').setAttribute('aria-expanded',open?'true':'false')};document.querySelectorAll('#mobileNav a').forEach(a=>a.onclick=()=>{el('mobileNav').classList.remove('open');el('menuBtn').setAttribute('aria-expanded','false')});
el('leadForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);const subject=encodeURIComponent('Заявка на стеклянную бутылку');const body=encodeURIComponent(`Имя: ${f.get('name')}\nТелефон: ${f.get('phone')}\nКомпания: ${f.get('company')}\nМодель: ${f.get('product')}\nКомментарий: ${f.get('message')}`);window.location.href=`mailto:info@vct-vladimir.ru?subject=${subject}&body=${body}`;});
render();
