const productsEl=document.getElementById('products'),search=document.getElementById('search'),neck=document.getElementById('neck'),category=document.getElementById('category'),counter=document.getElementById('counter'),mobileCounter=document.getElementById('mobileCounter');
const minVolume=document.getElementById('minVolume'),maxVolume=document.getElementById('maxVolume'),minVolumeOut=document.getElementById('minVolumeOut'),maxVolumeOut=document.getElementById('maxVolumeOut');
const imageModal=document.getElementById('imageModal'),detailModal=document.getElementById('detailModal'),zoomImage=document.getElementById('zoomImage'),zoomStage=document.getElementById('zoomStage');
let scale=1,ox=0,oy=0,dragging=false,sx=0,sy=0;
const catNames={soft:'Безалкогольные напитки',strong:'Крепкий алкоголь',still:'Тихие вина',sparkling:'Игристые вина',food:'Пищевые продукты / масла'};
function decodeUnicodeName(s){return String(s).replace(/#U([0-9A-Fa-f]{4})/g,(_,h)=>String.fromCharCode(parseInt(h,16)));}
const ruLatin={'А':'A','Б':'B','В':'V','Г':'G','Д':'D','Е':'E','Ё':'E','Ж':'Zh','З':'Z','И':'I','Й':'Y','К':'K','Л':'L','М':'M','Н':'N','О':'O','П':'P','Р':'R','С':'S','Т':'T','У':'U','Ф':'F','Х':'Kh','Ц':'Ts','Ч':'Ch','Ш':'Sh','Щ':'Sch','Ъ':'','Ы':'Y','Ь':'','Э':'E','Ю':'Yu','Я':'Ya','а':'a','б':'b','в':'v','г':'g','д':'d','е':'e','ё':'e','ж':'zh','з':'z','и':'i','й':'y','к':'k','л':'l','м':'m','н':'n','о':'o','п':'p','р':'r','с':'s','т':'t','у':'u','ф':'f','х':'kh','ц':'ts','ч':'ch','ш':'sh','щ':'sch','ъ':'','ы':'y','ь':'','э':'e','ю':'yu','я':'ya'};
function latinFileName(s){s=decodeUnicodeName(s);s=s.split('').map(c=>ruLatin[c]??c).join('');s=s.replace(/[^A-Za-z0-9._-]+/g,'_').replace(/_+/g,'_').replace(/^[_\-.]+|[_\-.]+$/g,'');return s||'image';}
function imgPath(name){return 'assets/images/'+encodeURIComponent(latinFileName(name)).replace(/%2F/g,'/');}
function neckKey(p){const n=decodeUnicodeName(p.name);const m=n.match(/(?:ТО|TO)-?\s*(\d+)|(?:КПМ|КПН|КПМ-3М|КПМ-3)-?(\d+)|(?:ВН?|В)-?(\d+)/i);if(!m)return 'Другое';return 'серия '+(m[1]||m[2]||m[3]);}
function initNecks(){const vals=[...new Set(PRODUCTS.map(neckKey))].sort((a,b)=>a.localeCompare(b,'ru',{numeric:true}));neck.innerHTML='<option value="">Все</option>'+vals.map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join('');document.getElementById('totalModels').textContent=PRODUCTS.length;}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function render(){let lo=+minVolume.value,hi=+maxVolume.value;if(lo>hi){[lo,hi]=[hi,lo]}minVolumeOut.value=lo;maxVolumeOut.value=hi;const q=search.value.toLowerCase().trim(),c=category.value,n=neck.value;const arr=PRODUCTS.filter(p=>{const name=decodeUnicodeName(p.name),pv=Number(p.volume)||0;return(!q||name.toLowerCase().includes(q))&&(!c||p.category===c)&&(!n||neckKey(p)===n)&&pv>=lo&&pv<=hi});counter.textContent=`Найдено: ${arr.length}`;if(mobileCounter)mobileCounter.textContent=`${arr.length} моделей`;productsEl.innerHTML=arr.map(p=>{const i=PRODUCTS.indexOf(p),name=decodeUnicodeName(p.name),src=imgPath(p.images[0]);return `<article class="card"><div class="card-photo" data-i="${i}"><img src="${src}" alt="Стеклянная бутылка ${escapeHtml(name)}" loading="lazy" onerror="this.style.display='none'"></div><div class="card-body"><h3>${escapeHtml(name)}</h3><div class="meta">${p.volume?p.volume+' мл':'Объём уточняется'} · ${escapeHtml(neckKey(p))} · ${escapeHtml(catNames[p.category]||'Стеклянная тара')}</div><div class="actions"><button class="primary" data-detail="${i}">Подробнее</button><button data-order="${i}">Запросить цену</button></div></div></article>`}).join('')||'<p>По вашему запросу ничего не найдено.</p>';}
function openImage(p){scale=1;ox=oy=0;zoomImage.src=imgPath(p.images[0]);zoomImage.alt=decodeUnicodeName(p.name);apply();imageModal.classList.add('open');imageModal.setAttribute('aria-hidden','false');}
function apply(){zoomImage.style.transform=`translate(${ox}px,${oy}px) scale(${scale})`;}
function zoom(d){scale=Math.min(5,Math.max(.6,scale+d));apply();}
function openDetail(p){const name=decodeUnicodeName(p.name);document.getElementById('detailContent').innerHTML=`<div class="detail-content"><div class="detail-photo"><img src="${imgPath(p.images[0])}" alt="Стеклянная бутылка ${escapeHtml(name)}"></div><div class="detail-info"><div class="eyebrow">КАТАЛОГ</div><h2>${escapeHtml(name)}</h2><table class="detail-table"><tr><td>Объём</td><td>${p.volume?p.volume+' мл':'Уточняется'}</td></tr><tr><td>Серия венчика</td><td>${escapeHtml(neckKey(p))}</td></tr><tr><td>Категория</td><td>${escapeHtml(catNames[p.category]||'Стеклянная тара')}</td></tr><tr><td>Фотографий</td><td>${p.images.length}</td></tr></table><p>Точные технические параметры, масса, высота, диаметр и условия поставки уточняются по запросу для конкретной партии.</p><button class="btn" onclick="orderProduct(${PRODUCTS.indexOf(p)})">Запросить цену</button></div></div>`;detailModal.classList.add('open');detailModal.setAttribute('aria-hidden','false');}
function orderProduct(i){const p=PRODUCTS[i];document.getElementById('productField').value=decodeUnicodeName(p.name);detailModal.classList.remove('open');document.getElementById('contacts').scrollIntoView({behavior:'smooth'});}
productsEl.addEventListener('click',e=>{const photo=e.target.closest('.card-photo'),det=e.target.closest('[data-detail]'),ord=e.target.closest('[data-order]');if(photo)openImage(PRODUCTS[+photo.dataset.i]);if(det)openDetail(PRODUCTS[+det.dataset.detail]);if(ord)orderProduct(+ord.dataset.order);});
[search,neck,category,minVolume,maxVolume].forEach(x=>x.addEventListener('input',render));document.getElementById('resetFilters').onclick=()=>{search.value='';neck.value='';category.value='';minVolume.value=100;maxVolume.value=1000;render();};
document.getElementById('closeImage').onclick=()=>imageModal.classList.remove('open');document.getElementById('closeDetail').onclick=()=>detailModal.classList.remove('open');document.getElementById('zoomIn').onclick=()=>zoom(.25);document.getElementById('zoomOut').onclick=()=>zoom(-.25);document.getElementById('zoomReset').onclick=()=>{scale=1;ox=oy=0;apply();};
zoomStage.addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY<0?.2:-.2);},{passive:false});zoomStage.addEventListener('mousedown',e=>{dragging=true;sx=e.clientX-ox;sy=e.clientY-oy;});window.addEventListener('mousemove',e=>{if(dragging){ox=e.clientX-sx;oy=e.clientY-sy;apply();}});window.addEventListener('mouseup',()=>dragging=false);
window.addEventListener('keydown',e=>{if(e.key==='Escape'){imageModal.classList.remove('open');detailModal.classList.remove('open');filters.classList.remove('open');backdrop.classList.remove('open');}});
document.getElementById('leadForm').addEventListener('submit',e=>{e.preventDefault();alert('Заявка заполнена. Подключите отправку формы к почте или CRM перед публикацией.');});
const menuToggle=document.getElementById('menuToggle'),siteNav=document.getElementById('siteNav');menuToggle.addEventListener('click',()=>{const open=siteNav.classList.toggle('open');menuToggle.setAttribute('aria-expanded',String(open));});siteNav.addEventListener('click',e=>{if(e.target.tagName==='A')siteNav.classList.remove('open');});
const mobileBtn=document.getElementById('mobileFiltersBtn'),filters=document.getElementById('filters'),backdrop=document.getElementById('mobileBackdrop');if(mobileBtn){mobileBtn.addEventListener('click',()=>{filters.classList.add('open');backdrop.classList.add('open');});backdrop.addEventListener('click',()=>{filters.classList.remove('open');backdrop.classList.remove('open');});}
initNecks();render();
